version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8081
      - CUSTOMER_SERVICE_URL=http://customer-service:8082
      - SALES_SERVICE_URL=http://sales-service:8083
      - ANALYTICS_SERVICE_URL=http://analytics-service:8084
      - RECOMMENDATION_SERVICE_URL=http://recommendation-service:8085
      - CHATBOT_SERVICE_URL=http://chatbot-service:8086

  auth-service:
    build: ./auth-service
    ports:
      - "8081:8081"

  customer-service:
    build: ./customer-service
    ports:
      - "8082:8082"

  sales-service:
    build: ./sales-service
    ports:
      - "8083:8083"

  analytics-service:
    build: ./analytics-service
    ports:
      - "8084:8084"

  recommendation-service:
    build: ./recommendation-service
    ports:
      - "8085:8085"

  chatbot-service:
    build: ./chatbot-service
    ports:
      - "8086:8086"

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: crmind
      POSTGRES_USER: crmind_user
      POSTGRES_PASSWORD: crmind_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
